# Scrapping Data Disney+ Google Playstore

Antonius Vincent Jung - CACC012D6Y2282 - CAC-15

Saya akan menggunakan data Disney+ dari Google PlayStore, dengan total rating dan ulasan sebanyak 30.000 data paling relevan yang berasal dari Indonesia. Disini saya hanya akan menyimpan atribut reviewId, score, dan content yang relevan untuk pre-processing dan pelatihan data.

## Install library

In [1]:
!pip install google-play-scraper pandas

Collecting google-play-scraper
  Downloading google_play_scraper-1.2.7-py3-none-any.whl.metadata (50 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.2/50.2 kB 2.4 MB/s eta 0:00:00
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading google_play_scraper-1.2.7-py3-none-any.whl (28 kB)
Installing collected packages: google-play-scraper
Successfully installed google-play-scraper-1.2.7

## Import Library

In [2]:
import pandas as pd
from google_play_scraper import reviews, Sort

## Scrapping data

In [3]:
raw_reviews,continuation_token = reviews(
    'in.startv.hotstar.dplus',
    lang='id',
    country='id',
    sort=Sort.MOST_RELEVANT,
    count=30000
)

len(raw_reviews)

30000

## Ubah Hasil Scrapping menjadi DataFrame

In [4]:
df = pd.DataFrame(raw_reviews)
df.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,974dd8bb-d007-4fef-bc07-5bdf21475226,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"Udah beli paket dari XL, saat log in kode OTP ...",1,5,26.02.16.5,2026-03-08 12:06:33,None,NaT,26.02.16.5
1,0c9f7e33-3fb2-432c-8760-cd0564aae4a5,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"Tambah lama, tambah ribet. sudah beli premium ...",2,4,26.02.16.5,2026-03-05 11:47:32,None,NaT,26.02.16.5
2,afdf6a08-2b68-459c-98a3-033738bb2f52,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,tolong dong aku udah berlangganan melalui myte...,1,2,26.02.16.5,2026-03-12 05:15:10,"Hai, kami mohon maaf atas kendala yang kamu al...",2026-03-12 09:46:30,26.02.16.5
3,d168a07f-fdf9-4d46-a16f-a3f3f9c800ba,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,udah beli premium yg katanya bisa untuk bebera...,1,3,26.02.16.5,2026-03-11 10:07:18,Hai! Mohon maaf atas ketidaknyamannya. Mohon k...,2026-03-12 09:07:48,26.02.16.5
4,e2599e40-ef84-4239-b13e-6b926b856511,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Ternyata aplikasi nya beneran jelek ya. Baru a...,1,4,26.02.16.5,2026-03-06 04:33:48,"Hai Arsyr, kami mohon maaf atas kendala yang k...",2026-03-06 08:11:21,26.02.16.5

## Seleksi Fitur
Fitur yang akan digunakan:
- reviewId (untuk pengecekan duplikat)
- score / rating
- content / ulasan

In [5]:
df = df[["reviewId","score", "content"]]

df.head()

,reviewId,score,content
0,974dd8bb-d007-4fef-bc07-5bdf21475226,1,"Udah beli paket dari XL, saat log in kode OTP ..."
1,0c9f7e33-3fb2-432c-8760-cd0564aae4a5,2,"Tambah lama, tambah ribet. sudah beli premium ..."
2,afdf6a08-2b68-459c-98a3-033738bb2f52,1,tolong dong aku udah berlangganan melalui myte...
3,d168a07f-fdf9-4d46-a16f-a3f3f9c800ba,1,udah beli premium yg katanya bisa untuk bebera...
4,e2599e40-ef84-4239-b13e-6b926b856511,1,Ternyata aplikasi nya beneran jelek ya. Baru a...

## Cek Duplikat dan Data Null

In [6]:
print("Jumlah data:", len(df))
print("\nJumlah duplikat reviewId:", df.duplicated(subset=["reviewId"]).sum())
print("\nMissing values:")
print(df.isnull().sum())

Jumlah data: 30000

Jumlah duplikat reviewId: 0

Missing values:
reviewId    0
score       0
content     0
dtype: int64

## Cek Distribusi Rating

In [7]:
df["score"].value_counts().sort_index()

score
1    12567
2     2594
3     2910
4     2393
5     9536
Name: count, dtype: int64

## Simpan menjadi file CSV

In [8]:
OUTPUT_CSV = "disneyplus_reviews_raw.csv"
df.to_csv(OUTPUT_CSV, index=False, encoding="utf-8-sig")
print(f"File berhasil disimpan: {OUTPUT_CSV}")

File berhasil disimpan: disneyplus_reviews_raw.csv